### ISSUE TITLE
Herrores. 

### ISSUE THREAD

**Issue by DrlucasLL** [Greg-xh/Novelas#1]
571- "Pero mírenlas, las cosas volvieron a la normalidad, ¿no? Ustedes compensan (la debilidades) de cada una, es como si fueran una sola persona cuando están juntas."
*las debilidades* 

590- Mientras yo estuviera allí para despertarla, no llegará tarde. Mientras yo (este) ahí, su cabello estará siempre limpio y hermoso y jamás olvidará sus cosas.
*esté*

642- Futaba no era muy paciente, por eso, aunque me dijera que estaba de acuerdo, sabía que sería (un tarea) muy difícil.
*una tarea*

669- "Si puedes mantener tu promesa, haré (cualquier cosas) que me pidas como recompensa."
*cualquier cosa*

699- Le (dí) una palmadita en la cabeza y sonrió alegremente.
*di*

782- "¿Hay algo que pueda hacer para estar más tiempo con ella? Quiero estar a solas con ella, solas las dos, para (siempre....")
*siempre..."*

788- La puerta azotó con fuerza la pared, Futaba entró, pálida como una (sabana.)    
*Aquí depende de si se refiere a una "sábana" de las camas o a una "sabana" de campos. *

876- Levanté (su manos) sobre su cabeza, y le envolví la cinta alrededor de las muñecas.
*sus manos*

896- ("Ah..")
*"Ah..."*

1085- "Sí, mi (señora..")
*señora..."*

1132- (Asentí , y de) mi bolsillo le saqué un pequeño plástico en forma de huevo.
*Asentí, y de*

1213- "Tu rostro está rojo, ¿no tendrás (fiebre?.")
*fiebre?"*

1238- La intensidad dependía de cómo me sintiera ese día, todo el día la vigilaba en una esquina, y (todo los días) hacía que me jurara que no se correría sin mi permiso.
*todos los días*

1266- Día a día, cada vez que la castigaba, la llevaba a sus (limites) y terminó desmayada varias veces.
*límites*

1276- Asentí, la sometí (varías) veces a dolorosos castigos, pero eso no era lo que provocaba su fiebre. Por lo que al final, la mandaron a descansar en casa.
*varias*

1277- (Mi padres) no tardaron en relacionar el estado de Futaba con mis calificaciones.
*Mis padres*

1323- No me dijeron los detalles, pero el maestro y mis padres llegaron a la conclusión de que (mis malas calificaciones era por) estar tan enfocada en cuidar a Futaba.
*mis malas calificaciones eran por*

1326- "Te dije que te preocuparas por ti misma, ¿lo recuerdas? ¿Ahora lo entiendes? ¡Solo mira (lo que le ha pasado a tus calificaciones!")
*lo que les ha pasado a tus calificaciones!"*

**Comment by DrlucasLL** [comment]
71- Por ejemplo, debes (de mostrale) a mamá que puedes hacer tus cosas solas, sin mi ayuda."
*demostrarle*

123- "Con eso hecho... (¡que) te parece uno más!"
*qué*

150- "¿Crees que es mucha (azúcar?.")
*azúcar?"*

252- "Así como lo oyes, Futaba llegó tarde (todo los días de la semana) pasada. Estaba preparado para llamar a sus padres si volvía a llegar tarde esta semana."
*todos los días de la semana*

343- "Ohh, ¿y eso qué quiere (decir?.")
*decir?"*

428- Eso me hizo pensar... que seguía cometiendo (los mismo errores) que esta mañana.
*los mismos errores*

711- "Duis, Futaba, estás cubierta de crema."
¿Qué es ese Duis? ¿Es un error o simplemente no lo entendí? 

858- Lamí hasta llegar a (su pechos.) Quería quitarle el sostén y empezar a lamerle los pezones.
*sus pechos*

907- Mientras se lo susurraba, con mis uñas apretaba su clítoris, haciendo que sus hombros (vovlieran) a sacudirse, luego, con mis yemas, (empece) a acariciarlo y así Futaba empezó a gemir. 
*volvieran* / *empecé*

1059- Futaba se enojó, pero (su mejillas se sonrojaron) por un instante cuando le dije que era linda.
*sus mejillas se sonrojaron*

1087- Dado lo que sucedió en el almuerzo, me hice cargo de la cena. Mientras cortaba el repollo, Futaba (le daba forma a las hamburguesas.)
*les daba forma a las hamburguesas.* 

1146- "¡¿Cómo voy a (sa...?) ¡Aah! F-Futaba, no los toques."
*sa...?!*

1206- El estómago de Futaba gruñó muy (fuerte..)
Aquí no sé si lo correcto es sólo un punto o tres, pero no creo que sean dos. 


1263- Futaba alzó los brazos y giró, mientras en mi rostro se formaba (un sonrisa.)
*una sonrisa* 

1424- Como gemelas idénticas, nuestros rostros eran parecidos. Pero (nuestra manera de pensar, vestir y actuar eran completamente opuestas), así que era imposible ser confundidas, aunque a menudo, nos decían lo mucho que nos parecíamos.
Aquí se senti algo raro cuando lo leí, y creo que así es más correcto: *nuestras maneras de pensar, vestir y actuar eran completamente opuesta* 

1431- Fue un pequeño beso en los labios. Futaba había salido de (su prácticas), y como estábamos tan cerca, podía oler su dulce sudor.
*su práctica* 

1462- Solo bromeaba. La verdad era que el beso fue mucho (mas) suave de lo habitual.
*más*

1510- Cuando Futaba se perdió en mis besos, le alcé la falda y (empece) a acariciar sus partes íntimas.
*empecé*

1527- Tembló cuando susurré su nombre. Reí y le (susurre) con lujuria:
*susurré*

1542- (Sus pantis ya estaba mojados), y su clítoris erecto, por lo que no se me dificultó encontrarlo.
*Sus pantis ya estaban mojados* 

1635- Un poco aturdida, (Furaba) pudo quitarse el sostén, haciendo que sus pechos salieran y se sacudieran libremente.
¿No es *Futaba*? 

1864- Sacudí la cabeza tratando de aclarar (mi ideas.)
*mis ideas.*

**Comment by Greg-xh** [comment]
Gracias, wucas.
